rvm:
  - 2.0.0
  - 2.1
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head

before_script:
  - "./spec/script/example_target_host &"
  - "./spec/script/example_translating_proxy &"
  - "sleep 5"
